---

- name: deploy ist-lukas-schon-wach.lol
  hosts: oracle
  remote_user: svenstaro
  become: yes
  become_user: root
  vars:
    site_path: /srv/ilswlol
  tasks:
  - name: pull git repo
    register: gitstatus
    git: accept_hostkey=yes
         force=yes
         recursive=yes
         repo=git://github.com/svenstaro/ilswlol.git
         dest={{ site_path }}

  - name: create telegram home directory
    file: owner=http group=root mode=750 state=directory path=/var/lib/ilswlol

  - name: create nginx log directory
    file: owner=http group=log mode=750 state=directory path=/var/log/nginx/ist-lukas-schon-wach.lol

  - name: configure uwsgi
    template: src=ilswlol_uwsgi.ini.j2 dest=/etc/uwsgi/vassals/ilswlol.ini owner=root group=http mode=640

  - name: configure nginx
    template: src=ilswlol_nginx.conf.j2 dest=/etc/nginx/vhosts/ilswlol.conf owner=root group=root mode=644
    notify:
      - restart nginx

  - name: reload nginx
    service: name=nginx state=reloaded enabled=yes

  - name: touch uwsgi vassal
    file: state=touch path=/etc/uwsgi/vassals/ilswlol.ini

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
